apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: my-network
spec:
  config: '{
    "cniVersion": "0.3.0",
    "name": "my-network",
    "type": "macvlan",
    "master": "wlp0s20f3",
    "mode": "bridge",
    "isDefaultgateway": true,
    "ipam": {
      "type": "host-local",
      "ranges": [
         [ {
           "subnet": "10.60.200.0/21",
           "rangeStart": "10.60.200.100",
           "rangeEnd": "10.60.200.120",
           "gateway": "10.60.202.133"
         } ]
      ]
    }
  }'
