apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: my-network
spec:
  config: '{
    "cniVersion": "0.3.0",
    "name": "my-network",
    "type": "macvlan",
    "master": "br-201a3e9426e0",
    "mode": "bridge",
    "isDefaultgateway": true,
    "ipam": {
      "type": "host-local",
      "ranges": [
         [ {
           "subnet": "192.168.49.0/24",
           "rangeStart": "192.168.49.100",
           "rangeEnd": "192.168.49.120",
           "gateway": "192.168.49.1"
         } ]
      ]
    }
  }'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skuid-ign
  annotations:
    k8s.v1.cni.cncf.io/networks: my-network
spec:
  replicas: 1
  selector: 
    matchLabels:
      app : skuid-ign
  template:
    metadata:
      labels:
        app: skuid-ign
      annotations:
        k8s.v1.cni.cncf.io/networks: my-network
    spec:
      containers:
        - name: skuid-ignition
          image: renzobc/skuid_ignition:v-7.0
          env:
            - name: RMW_IMPLEMENTATION
              value: rmw_fastrtps_cpp
          volumeMounts:
            - mountPath: /root/.ignition/gazebo/log
              name: logs
      volumes:
        - name: logs
          persistentVolumeClaim: 
            claimName: host-pv-log-data-claim
